on:
    push:
        tags:
            - 'v*'
name: Publish package
jobs:
    release:
        name: Publish package
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            #Use this github action
            - name: Check package version
              uses: technote-space/package-version-check-action@v1
              with:
                COMMIT_DISABLED: 1

            - name: Install package dependencies
              run: npm install

            - name: Build
              run: npm build

            - name: Publish
              run: |
                npm config set //registry.npmjs.org/:_authToken=$ACTIONS_DEPLOY_ACCESS_TOKEN
                npm publish
              env:
                NPM_AUTH_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}